export enum PlayerSkin {
  None = 0,
  Astronaut = 1,
  Captain = 2,
  Mechanic = 3,
  Military = 4,
  Police = 5,
  Scientist = 6,
  SuitBlack = 7,
  SuitWhite = 8,
  WallGuard = 9,
  Hazmat = 10,
  SecurityGuard = 11,
  Tarmac = 12,
  Miner = 13,
  Winter = 14,
  Archaeologist = 15,
};
