export enum InnerNetObjectType {
  LobbyBehaviour,
  GameData,
  VoteBanSystem,
  PlayerControl,
  PlayerPhysics,
  CustomNetworkTransform,
  MeetingHud,
  SkeldShipStatus,
  DleksShipStatus,
  MiraShipStatus,
  PolusShipStatus,
  AirshipStatus,
  SubmergedStatus,
}
