export enum SpawnType {
  SkeldShipStatus = 0,
  MeetingHud = 1,
  LobbyBehaviour = 2,
  GameData = 3,
  PlayerControl = 4,
  MiraShipStatus = 5,
  PolusShipStatus = 6,
  DleksShipStatus = 7,
  AirshipStatus = 8,
  SubmergedStatus = 9,
  PolusButton = 10,
  PolusCameraController = 11,
  PolusConsole = 12,
  PolusDeadBody = 13,
  PolusImage = 14,
  PolusLightSource = 15,
  PolusPointOfInterest = 16,
  PolusSoundSource = 17,
  PolusVent = 18,
}
